/* AUTO-GENERATED by tests/bredr/gen_151FC475.c -- LAP 0x001FC475 */
#ifndef CAPTURE_151FC475_H
#define CAPTURE_151FC475_H
#include <stdint.h>
#define CAP_LAP 0x001FC475u
#define CAP_TRUE_UAP 0x15u
#define CAP_TRUE_NAP 0x00u
typedef struct { uint64_t header_raw; uint16_t air_payload_bits; uint8_t air_payload[256]; uint32_t clkn; uint8_t channel; } cap_pkt_t;
static const cap_pkt_t cap_151FC475[20] = {
  { 0x0000038E38FC0E07u, 0, {}, 256u, 0u },
  { 0x000703FE00E00E00u, 0, {}, 258u, 7u },
  { 0x000703F03FFF8E3Fu, 0, {}, 260u, 14u },
  { 0x0000038007E38E38u, 0, {}, 262u, 21u },
  { 0x0038E38E381C7FC7u, 0, {}, 264u, 28u },
  { 0x003FE3FE00007FC0u, 0, {}, 266u, 35u },
  { 0x003FE3F03F1FFFFFu, 0, {}, 268u, 42u },
  { 0x0038E3800703FFF8u, 0, {}, 270u, 49u },
  { 0x0000FF81C0E00E07u, 0, {}, 272u, 56u },
  { 0x0007FFF1F8FC0E00u, 0, {}, 274u, 63u },
  { 0x0007FFFFC7E38E3Fu, 0, {}, 276u, 70u },
  { 0x0000FF8FFFFF8E38u, 0, {}, 278u, 77u },
  { 0x00381F81C0007FC7u, 0, {}, 280u, 5u },
  { 0x003F1FF1F81C7FC0u, 0, {}, 282u, 12u },
  { 0x003F1FFFC703FFFFu, 0, {}, 284u, 19u },
  { 0x00381F8FFF1FFFF8u, 0, {}, 286u, 26u },
  { 0x00381FFFC7FFFFC7u, 0, {}, 288u, 33u },
  { 0x003F1F8FFFE3FFC0u, 0, {}, 290u, 40u },
  { 0x003F1F81C0FC7FFFu, 0, {}, 292u, 47u },
  { 0x003803F038E38FC7u, 56, {0x73u,0x79u,0xEDu,0x9Au,0x5Du,0xF3u,0xB0u}, 294u, 54u },
};
static const int cap_151FC475_n = 20;
#endif
