/*
 * OFFLINE capture generator for LAP 0x151FC475 using libbtbb reference.
 * Not part of shipped product. Generates tests/bredr/capture_151FC475.h
 *
 * Compile: cc tests/bredr/gen_151FC475.c -o /tmp/gen_151FC475 && /tmp/gen_151FC475 > tests/bredr/capture_151FC475.h
 */
#include <stdio.h>
#include <stdint.h>
#include <string.h>

/* ---- libbtbb reference (verbatim) ---- */
static uint8_t lb_reverse_byte(uint8_t b)
{
    b = (uint8_t)(((b & 0xF0) >> 4) | ((b & 0x0F) << 4));
    b = (uint8_t)(((b & 0xCC) >> 2) | ((b & 0x33) << 2));
    b = (uint8_t)(((b & 0xAA) >> 1) | ((b & 0x55) << 1));
    return b;
}
static uint8_t lb_uap_from_hec(uint16_t data, uint8_t hec)
{
    int i;
    for (i = 9; i >= 0; i--) {
        if (hec & 0x80) hec ^= 0x65;
        hec = (uint8_t)((hec << 1) | (((hec >> 7) ^ (data >> i)) & 0x01));
    }
    return lb_reverse_byte(hec);
}
static const uint8_t LB_WHITENING_DATA[] = {1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1};
static const uint8_t LB_INDICES[] = {99, 85, 17, 50, 102, 58, 108, 45, 92, 62, 32, 118, 88, 11, 80, 2, 37, 69, 55, 8, 20, 40, 74, 114, 15, 106, 30, 78, 53, 72, 28, 26, 68, 7, 39, 113, 105, 77, 71, 25, 84, 49, 57, 44, 61, 117, 10, 1, 123, 124, 22, 125, 111, 23, 42, 126, 6, 112, 76, 24, 48, 43, 116, 0};
static uint16_t lb_crcgen(char *payload, int length, int UAP)
{
    char bit;
    uint16_t reg, count;
    reg = (lb_reverse_byte((uint8_t)UAP) << 8) & 0xff00;
    for (count = 0; count < (uint16_t)length; count++) {
        bit = payload[count];
        reg = (uint16_t)((reg >> 1) | (((reg & 0x0001) ^ (bit & 0x01)) << 15));
        reg = (uint16_t)(reg ^ ((reg & 0x8000) >> 5));
        reg = (uint16_t)(reg ^ ((reg & 0x8000) >> 12));
    }
    return reg;
}
static int lb_forward_hec(uint16_t data, uint8_t uap)
{
    for (int h = 0; h < 256; h++)
        if (lb_uap_from_hec(data, (uint8_t)h) == uap)
            return h;
    return -1;
}

typedef struct {
    uint64_t header_raw;
    uint8_t air_payload[256];
    unsigned int air_payload_bits;
} cap_frame_t;

static void build_header_frame(uint16_t header_data, uint8_t uap, uint8_t clk6, cap_frame_t *frame)
{
    memset(frame, 0, sizeof(*frame));
    int hec = lb_forward_hec(header_data, uap);
    if (hec < 0) hec = 0;
    uint8_t decoded[18];
    for (int i = 0; i < 10; i++) decoded[i] = (uint8_t)((header_data >> i) & 1u);
    for (int i = 0; i < 8; i++) decoded[10+i] = (uint8_t)(((uint8_t)hec >> i) & 1u);
    int idx = LB_INDICES[clk6 & 0x3f];
    uint8_t pre[18];
    for (int i = 0; i < 18; i++) { pre[i]= decoded[i] ^ LB_WHITENING_DATA[idx]; idx=(idx+1)%127; }
    uint64_t coded=0;
    for (int i=0;i<18;i++) for(int j=0;j<3;j++) coded |= ((uint64_t)(pre[i]&1u)) << (3*i+j);
    frame->header_raw = coded;
}

static void build_dh1_frame(uint16_t header_data, uint8_t uap, uint8_t clk6, const uint8_t *user, unsigned int user_len, cap_frame_t *frame)
{
    build_header_frame((uint16_t)((header_data & 0x07u) | (header_data & 0x380u) | ((uint16_t)0x04u<<3)), uap, clk6, frame);
    uint8_t dewhitened[256];
    unsigned int total = 1u + user_len + 2u;
    dewhitened[0]=(uint8_t)(0x02u|(0x01u<<2)|((user_len&0x1Fu)<<3));
    for(unsigned int i=0;i<user_len;i++) dewhitened[1+i]=user[i];
    char bits[2048];
    for(unsigned int i=0;i<(1u+user_len)*8u;i++) bits[i]=(char)((dewhitened[i/8u]>>(i%8u))&1u);
    uint16_t crc = lb_crcgen(bits, (int)((1u+user_len)*8u), uap);
    dewhitened[1+user_len]=(uint8_t)(crc&0xFFu);
    dewhitened[2+user_len]=(uint8_t)((crc>>8)&0xFFu);
    int idx = LB_INDICES[clk6 & 0x3f];
    idx = (idx+18)%127;
    memset(frame->air_payload,0,sizeof(frame->air_payload));
    for(unsigned int bit=0;bit<total*8u;bit++){
        uint8_t b=(uint8_t)((dewhitened[bit/8u]>>(bit%8u))&1u);
        b ^= LB_WHITENING_DATA[idx];
        if(b) frame->air_payload[bit/8u] |= (uint8_t)(1u<<(bit%8u));
        idx=(idx+1)%127;
    }
    frame->air_payload_bits = total*8u;
}

int main(void)
{
    const uint32_t LAP = 0x001FC475u; // LAP is 24-bit (lower 24 of 0x151FC475), UAP is separate
    // Correct BD_ADDR for this piconet: NAP:UAP:LAP = ??:0x15:0x1FC475
    const uint8_t TRUE_UAP = 0x15u; // user-confirmed correct UAP for LAP 0x1FC475
    const uint8_t TRUE_NAP = 0x00u;

    printf("/* AUTO-GENERATED by tests/bredr/gen_151FC475.c -- LAP 0x%08X */\n", LAP);
    printf("#ifndef CAPTURE_151FC475_H\n#define CAPTURE_151FC475_H\n");
    printf("#include <stdint.h>\n");
    printf("#define CAP_LAP 0x%08Xu\n", LAP);
    printf("#define CAP_TRUE_UAP 0x%02Xu\n", TRUE_UAP);
    printf("#define CAP_TRUE_NAP 0x%02Xu\n", TRUE_NAP);
    printf("typedef struct { uint64_t header_raw; uint16_t air_payload_bits; uint8_t air_payload[256]; uint32_t clkn; uint8_t channel; } cap_pkt_t;\n");

    // Find a pool of headers where TRUE_UAP is reachable (surjective after fix)
    uint16_t pool[1024]; int pool_n=0;
    for(int d=0;d<1024;d++) if(lb_forward_hec((uint16_t)d, TRUE_UAP)>=0) pool[pool_n++]=(uint16_t)d;
    int dh1_idx=-1;
    for(int i=0;i<pool_n;i++) if((pool[i]&0x78u)==0x20u){dh1_idx=i;break;}
    if(pool_n==0||dh1_idx<0){ fprintf(stderr,"no DH1 reachable for UAP 0x%02X\n",TRUE_UAP); return 1; }

    static const uint8_t user4[]={0x11,0x22,0x33,0x44};
    static const uint8_t user8[]={0xDE,0xAD,0xBE,0xEF,0xCA,0xFE,0xBA,0xBE};
    const int N=20;
    printf("static const cap_pkt_t cap_151FC475[%d] = {\n", N);
    for(int k=0;k<N;k++){
        uint32_t clkn = (uint32_t)(0x100 + k*2); // even clkn steps, realistic
        /* Production clock model: whitening clock is CLK1-6 = (clkn>>1)&0x3f
         * (libbtbb's btbb_packet_set_data stores clkn >> 1). */
        uint8_t clk6 = (uint8_t)((clkn >> 1) & 0x3f);
        uint8_t ch = (uint8_t)((k*7)%79);
        uint16_t data = (k==N-1) ? pool[dh1_idx] : pool[k%pool_n];
        cap_frame_t f;
        if(k%5==0) { // mix FHS-like: use DM1 for variety, handled as DM1 in crc_check
            // For this synthetic capture we use DH1 for CRC-carrying packets, header-only otherwise
            // Keep header-only for k != N-1
            if(k==N-1) build_dh1_frame(data, TRUE_UAP, clk6, user8, 8, &f);
            else build_header_frame(data, TRUE_UAP, clk6, &f);
        } else {
            if(k==N-1) build_dh1_frame(data, TRUE_UAP, clk6, user4, 4, &f);
            else build_header_frame(data, TRUE_UAP, clk6, &f);
        }
        printf("  { 0x%016llXu, %u, {", (unsigned long long)f.header_raw, f.air_payload_bits);
        unsigned int nbytes=(f.air_payload_bits+7u)/8u;
        for(unsigned int i=0;i<nbytes;i++) printf("0x%02Xu%s", f.air_payload[i], i+1==nbytes?"":",");
        printf("}, %uu, %uu },\n", clkn, ch);
    }
    printf("};\n");
    printf("static const int cap_151FC475_n = %d;\n", N);
    printf("#endif\n");
    return 0;
}
